### ISSUE TITLE
Disabled Submit button

### ISSUE THREAD

**Issue by cmaustnu** [NationalUniversitySystem/info-theme#90]
The submit button is disabled by default until the GDPR / Consent field is checked.

An outlier RFI uses this field, however the checkbox is visually hidden as it's not a part of their flow.

[This causes the submit button to be forever disabled. ](https://github.com/NationalUniversitySystem/info-theme/blob/master/src/js/forms/submit-button.js#L12-L18)

A possible solution might be to check if the consent field is required or not, before disabling the submit button.

**Comment by mestradanu** [comment]
Good point on checking if the field is required or not. Can check for the attribute.
